services:
  app:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:1.25.1
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    ports:
      - "80:80"
    depends_on:
      - app
