# Generated by Django 4.2.3 on 2023-07-25 05:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_comment_parent_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
