# Generated by Django 4.2.3 on 2023-07-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_author_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="post_pictures"),
        ),
    ]
