# Generated by Django 4.2.3 on 2023-07-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_post_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
