# Generated by Django 4.2.3 on 2023-07-19 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_post_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="is_deleted",
        ),
    ]
